import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ImagePlus } from "lucide-react";
import { toast } from "sonner";
import { uploadNoticeImage, useNotice, useSaveNotice } from "../../../api/notice.api";
import MarkdownContent from "../../../components/MarkdownContent";
export default function NoticeEditor(){const id=Number(useParams().noticeId);const editing=Number.isFinite(id);const{data}=useNotice(editing?id:undefined);const[title,setTitle]=useState("");const[content,setContent]=useState("");const[pinned,setPinned]=useState(false);const[uploading,setUploading]=useState(false);const input=useRef<HTMLInputElement>(null);const nav=useNavigate();const save=useSaveNotice();useEffect(()=>{if(data){setTitle(data.title);setContent(data.content);setPinned(data.pinned)}},[data]);
 const image=async(file?:File)=>{if(!file)return;setUploading(true);try{const url=await uploadNoticeImage(file);setContent(v=>`${v}${v&&!v.endsWith("\n")?"\n":""}![이미지 설명](${url})\n`);toast.success("이미지를 본문에 추가했습니다.")}catch{toast.error("이미지 업로드에 실패했습니다.")}finally{setUploading(false)}};
 const submit=()=>{if(!title.trim()||!content.trim())return toast.warning("제목과 본문을 입력해주세요.");save.mutate({id:editing?id:undefined,input:{title,content,pinned}},{onSuccess:()=>{toast.success(editing?"공지사항을 수정했습니다.":"공지사항을 게시했습니다.");nav("/admin/notices")},onError:()=>toast.error("공지사항을 저장하지 못했습니다.")})};
 return <div className="min-h-screen w-screen bg-[#060a0c] text-white"><div className="border-b border-white/10 px-8 py-4"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><button onClick={()=>nav("/admin/notices")} className="text-sm text-neutral-400">← 나가기</button><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-sm text-neutral-300"><input type="checkbox" checked={pinned} onChange={e=>setPinned(e.target.checked)}/> 중요 공지로 고정</label><button disabled={save.isPending} onClick={submit} className="bg-emerald-500 px-5 py-2 text-sm font-bold text-black disabled:opacity-50">{save.isPending?"저장 중...":editing?"수정 완료":"게시하기"}</button></div></div></div>
 <div className="mx-auto grid max-w-[1500px] grid-cols-2 divide-x divide-white/10"><section className="min-h-[calc(100vh-73px)] p-10"><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} placeholder="제목을 입력하세요" className="w-full border-none bg-transparent text-4xl font-bold outline-none placeholder:text-neutral-700"/><div className="my-7 h-1 w-16 bg-neutral-500"/><div className="mb-3 flex items-center gap-2"><button disabled={uploading} onClick={()=>input.current?.click()} className="flex items-center gap-2 border border-white/15 px-3 py-2 text-sm text-neutral-300 hover:bg-white/5"><ImagePlus className="h-4 w-4"/>{uploading?"업로드 중...":"이미지 첨부"}</button><span className="text-xs text-neutral-600">마크다운 문법을 지원합니다.</span><input ref={input} type="file" accept="image/png,image/jpeg,image/gif,image/webp" hidden onChange={e=>void image(e.target.files?.[0])}/></div><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="내용을 입력하세요.\n\n# 제목\n- 목록\n**굵게**" className="min-h-[650px] w-full resize-none bg-transparent font-mono text-[16px] leading-8 outline-none placeholder:text-neutral-700"/></section><section className="min-h-[calc(100vh-73px)] bg-[#0a0f13] p-10"><p className="mb-8 text-xs tracking-[.14em] text-neutral-600">PREVIEW</p><h1 className="break-words text-4xl font-bold">{title||"제목 미리보기"}</h1><div className="my-8 border-t border-white/10"/><MarkdownContent content={content||"작성한 내용이 여기에 표시됩니다."}/></section></div></div>}
