import { Activity, AlertTriangle, CheckCircle2, Gauge, RefreshCw, ShieldAlert, Users, XCircle } from "lucide-react";
import OperationsIssues from "./OperationsIssues";
import { useOperationsIncidents, useOperationsInventory, useOperationsOverview, useOperationsReadiness, useOperationsTimeline } from "../../../api/securityMonitoring.api";

const n=(v?:number)=>Number(v||0).toLocaleString();
const duration=(s:number)=>s<60?`${s}초`:s<3600?`${Math.floor(s/60)}분`:`${Math.floor(s/3600)}시간 ${Math.floor(s%3600/60)}분`;
export default function SecurityMonitoring(){
 const overview=useOperationsOverview(), timeline=useOperationsTimeline(60), inventory=useOperationsInventory(), readiness=useOperationsReadiness(), incidents=useOperationsIncidents();
 const d=overview.data, refresh=()=>{ void overview.refetch(); void timeline.refetch(); void inventory.refetch(); void readiness.refetch(); void incidents.refetch(); };
 if(overview.isLoading) return <Shell><p className="mt-12 text-neutral-400">운영 상태를 불러오는 중입니다.</p></Shell>;
 if(!d) return <Shell><p className="mt-12 text-red-300">운영 정보를 불러오지 못했습니다.</p><OperationsIssues/></Shell>;
 const status=d.status==="HEALTHY"?{label:"정상 운영 중",style:"text-emerald-300 border-emerald-900 bg-emerald-950/30",icon:CheckCircle2}:d.status==="WARNING"?{label:"확인이 필요한 항목이 있습니다",style:"text-amber-300 border-amber-900 bg-amber-950/30",icon:AlertTriangle}:{label:"즉시 확인이 필요합니다",style:"text-red-300 border-red-900 bg-red-950/30",icon:XCircle};
 const StatusIcon=status.icon;
 return <Shell><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs tracking-[.22em] text-neutral-500">LIVE OPERATIONS</p><h1 className="mt-2 text-3xl font-bold">운영 모니터링</h1><p className="mt-2 text-sm text-neutral-400">예약·보안 이슈·재고·서버 상태를 한 화면에서 확인합니다.</p></div><button onClick={refresh} className="flex items-center gap-2 rounded-lg border border-neutral-700 px-4 py-2 text-sm hover:bg-neutral-800"><RefreshCw size={15}/>전체 새로고침</button></div>
 <div className={`mt-7 flex items-center gap-3 rounded-xl border p-4 ${status.style}`}><StatusIcon size={20}/><strong>{status.label}</strong><span className="ml-auto text-xs text-neutral-500">{new Date(d.observedAt).toLocaleString("ko-KR")}</span></div>
 <section className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={Users} label="최근 5분 요청" value={`${n(d.lastFiveMinutes.requests)}건`} detail="전체 API 요청 (사용자 수 아님)"/><Kpi icon={Activity} label="최근 5분 예약 실패" value={`${n(d.lastFiveMinutes.reservationFailure)}건`} detail="품절 외 실패 사유 검토"/><Kpi icon={CheckCircle2} label="최근 5분 예약" value={`${n(d.lastFiveMinutes.reservationSuccess)}건`} detail={`재고 소진 ${n(d.lastFiveMinutes.reservationSoldOut)}건`}/><Kpi icon={Gauge} label="응답속도 p95" value={`${n(d.lastFiveMinutes.p95Ms)}ms`} detail={`평균 ${Math.round(d.lastFiveMinutes.averageMs)}ms`}/><Kpi icon={ShieldAlert} label="최근 5분 오류" value={`${n(d.lastFiveMinutes.serverErrors)}건`} detail={`요청 제한 ${n(d.lastFiveMinutes.rateLimited)}건`}/></section>
 <section className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Panel title="최근 60분 요청·예약 추이"><Trend points={timeline.data||[]}/></Panel><Panel title="활성 경고"><div className="space-y-2">{d.alerts.length?d.alerts.map(a=><div key={a.code} className={`rounded-lg border p-3 ${a.severity==="CRITICAL"?"border-red-900/70 bg-red-950/25":"border-amber-900/70 bg-amber-950/20"}`}><p className="font-semibold">{a.title}</p><p className="mt-1 text-sm text-neutral-400">{a.message}</p></div>):<Empty text="감지된 경고가 없습니다."/>}</div></Panel></section>
 <section className="mt-4"><Panel title="기자재 재고 및 최근 수요"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-neutral-500"><tr>{["모델","전체","예약 가능","예약","대여 중","사용 불가","최근 시도/성공"].map(x=><th key={x} className="border-b border-neutral-800 px-3 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{inventory.data?.map(x=><tr key={x.groupKey} className="border-b border-neutral-900"><td className="px-3 py-3 font-semibold">{x.displayName}</td><td className="px-3">{n(x.total)}</td><td className="px-3 font-semibold text-emerald-300">{n(x.available)}</td><td className="px-3">{n(x.reserved)}</td><td className="px-3">{n(x.rented)}</td><td className={x.unavailable?"px-3 text-red-300":"px-3"}>{n(x.unavailable)}</td><td className="px-3">{n(x.recentDemand.attempts)} / {n(x.recentDemand.success)}</td></tr>)}</tbody></table></div></Panel></section>
 <section className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title={`예약 당일 사전점검 ${readiness.data?`(${readiness.data.passed}/${readiness.data.total})`:""}`}><div className="grid gap-2 sm:grid-cols-2">{readiness.data?.checks.map(c=><div key={c.code} className="rounded-lg border border-neutral-800 p-3"><div className="flex items-center gap-2">{c.passed?<CheckCircle2 size={16} className="text-emerald-400"/>:<XCircle size={16} className="text-red-400"/>}<strong className="text-sm">{c.title}</strong>{c.required&&<span className="ml-auto text-[10px] text-neutral-500">필수</span>}</div><p className="mt-2 text-xs leading-5 text-neutral-500">{c.detail}</p></div>)}</div></Panel><Panel title="서버 자원"><div className="grid grid-cols-2 gap-3"><Stat label="DB 응답" value={`${d.health.databaseLatencyMs}ms`} good={d.health.databaseHealthy}/><Stat label="Redis 응답" value={`${d.health.redisLatencyMs}ms`} good={d.health.redisHealthy}/><Stat label="JVM 메모리" value={`${d.resources.heapPercent.toFixed(1)}%`}/><Stat label="시스템 CPU" value={d.resources.systemCpuPercent<0?"측정 전":`${d.resources.systemCpuPercent.toFixed(1)}%`}/><Stat label="DB 연결" value={`${d.resources.hikariActive}/${d.resources.hikariMaximum}`} detail={`대기 ${d.resources.hikariPending}`}/><Stat label="서버 가동시간" value={duration(d.resources.uptimeSeconds)}/></div></Panel></section>
 <section className="mt-4"><Panel title="최근 장애·보안 이벤트"><div className="divide-y divide-neutral-800">{incidents.data?.length?incidents.data.map((e,i)=><div key={`${e.occurredAt}-${i}`} className="grid gap-1 py-3 text-sm sm:grid-cols-[190px_1fr_180px]"><time className="text-neutral-500">{new Date(e.occurredAt).toLocaleString("ko-KR")}</time><span className="font-semibold text-red-300">{e.type}</span><span className="font-mono text-neutral-500">{e.subject}</span></div>):<Empty text="최근 장애 이벤트가 없습니다."/>}</div></Panel></section>
 <OperationsIssues/>
 </Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-[#060a0c] px-5 py-10 text-white sm:px-8"><div className="mx-auto max-w-[1500px]">{children}</div></main>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-xl border border-neutral-800 bg-[#0b1014] p-5"><h2 className="mb-4 font-semibold">{title}</h2>{children}</article>}
function Kpi({icon:Icon,label,value,detail}:{icon:typeof Users;label:string;value:string;detail:string}){return <article className="rounded-xl border border-neutral-800 bg-[#0b1014] p-4"><Icon size={18} className="text-neutral-500"/><p className="mt-4 text-xs text-neutral-500">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums">{value}</p><p className="mt-1 text-xs text-neutral-500">{detail}</p></article>}
function Stat({label,value,detail,good}:{label:string;value:string;detail?:string;good?:boolean}){return <div className="rounded-lg border border-neutral-800 p-4"><p className="text-xs text-neutral-500">{label}</p><p className={`mt-2 text-xl font-bold tabular-nums ${good===false?"text-red-300":""}`}>{value}</p>{detail&&<p className="mt-1 text-xs text-neutral-500">{detail}</p>}</div>}
function Empty({text}:{text:string}){return <p className="py-8 text-center text-sm text-neutral-500">{text}</p>}
function Trend({points}:{points:{requests:number;reservationSuccess:number;serverErrors:number;queueWaiting:number}[]}){const series=[{k:"requests",c:"#e5e7eb",l:"API 요청"},{k:"reservationSuccess",c:"#34d399",l:"예약 성공"},{k:"queueWaiting",c:"#60a5fa",l:"대기 인원"},{k:"serverErrors",c:"#f87171",l:"5xx"}] as const;const max=Math.max(1,...points.flatMap(p=>series.map(s=>p[s.k])));const path=(k:typeof series[number]["k"])=>points.map((p,i)=>`${i?"L":"M"}${(i/Math.max(1,points.length-1))*100},${46-(p[k]/max)*42}`).join(" ");return <div><div className="mb-3 flex flex-wrap gap-4 text-xs text-neutral-400">{series.map(s=><span key={s.k} className="flex items-center gap-2"><i className="h-2 w-2 rounded-full" style={{background:s.c}}/>{s.l}</span>)}</div><svg viewBox="0 0 100 50" className="h-56 w-full" preserveAspectRatio="none"><path d="M0 46H100" stroke="#262b30" strokeWidth=".4"/>{series.map(s=><path key={s.k} d={path(s.k)} fill="none" stroke={s.c} strokeWidth=".7" vectorEffect="non-scaling-stroke"/>)}</svg></div>}
