export type ModelItem = {
  modelId: number;
  categoryId: number;
  categoryName: string;
  type: string;
  name: string;
  displayName: string | null;
  subName: string | null;
  description: string | null;
  visibleToUsers: boolean;
  courseName: string;
  totalQty: number;
  availableQty: number;
  reservedQty: number;
  rentedQty: number;
  breakdownQty: number;
  lostQty: number;
  createdAt: string;
  updatedAt: string;
};